
name: NPM Publish

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --frozen-lockfile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
